# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to my site!
footer_title: What to contact me? Here''s how.
email: mikeyfreake@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My ramblings, thoughts, projects and playground relating to coding and software development. 
  Feel free to connect with me via email and Twitter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mikeyfreake.github.io" # the base hostname & protocol for your site
twitter_username: MaddFleaks
github_username:  mikeyfreake

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
